[ -n "$PS1" ] && source ~/.bash_profile

# added by travis gem
[ -f /Users/josh/.travis/travis.sh ] && source /Users/josh/.travis/travis.sh

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
